---
- hosts: centos_node1
  become: true
  vars:
    create_containers: 4
    default_container_name: docker
    default_container_image: ubuntu
    default_container_command: sleep 1d

  tasks:
    - name: Install required system packages
      yum: name={{ item }} state=latest update_cache=yes
      with_items:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        - python3 
        - python3-pip

    - name: Add Docker Repository
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: 0644

    - name: Install Docker latest version
      yum:
        name: docker-ce
        state: present

    - name: installing docker SDK
      command: "pip3 install docker"

    - name: Starting And Enabling Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Create default containers
      docker_container:
        name: "{{ default_container_name }}{{ item }}"
        image: "{{ default_container_image }}"
        command: "{{ default_container_command }}"
        state: present
      with_sequence: count={{ create_containers }}
